version: '3.8'
services:
  db:
    image: postgres:15
    networks:
      - myapp_network
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
 

  app:
    build: .
    networks:
      - myapp_network
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app 
      - /app/node_modules  
    command: npm run start:dev
networks:
  myapp_network:
    driver: bridge
volumes:
  pgdata: